
env:
  grid_x: 10
  grid_y: 10
  num_colors: 10
  num_actions: 10
  use_arc: True

train:
  nenvs: 80
  nsteps: 50
  ent_coef: 0.01
  base_lr: 3e-5
  vf_coef: 0.5
  aux_coef: 0.5
  max_grad_norm: 0.5
  gamma: 0
  lam: 0.95
  log_interval: 1
  nminibatches: 40
  noptepochs: 4
  cliprange: 0.1
  save_interval: 0
  total_timesteps: 20000000
  gpu_num: 1
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  cliprew: 10
  update_actor_after: 100
  
model:
  n_layer: 8
  n_head: 8
  n_embd: 512
  embd_pdrop: 0.1
  resid_pdrop: 0.1
  attn_pdrop: 0.1